import type { Metadata } from "next";
import "./globals.css";

import { FightProvider } from "@/context/fightContext";

export const metadata: Metadata = {
  title: "Azapfy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black text-white">
        <FightProvider>{children}</FightProvider>
      </body>
    </html>
  );
}
